# Travis CI script to invoke coveralls.io coverage reporting
# (C) 2015 Niall Douglas

language: cpp
os:
 - linux

notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always

before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq valgrind; fi
 - git submodule update --init --recursive

script:
 - make debug
 - ./test_utp_crust
 - valgrind ./test_utp_crust
 