version: 1.0.{build}
os: Visual Studio 2015 RC
configuration: Debug
platform: x86
build:
  project: libutp_crust.sln
  verbosity: minimal
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - git submodule update --init --recursive
test_script:
  - Debug\test_utp_crust.exe
